spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: 'create-drop'
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
